[package]
name = "axplat-arm-qemu-virt"
version = "0.3.0"
edition = "2024"

[features]
irq = ["axplat/irq"]
smp = ["axplat/smp"]
rtc = []
fp-simd = ["axcpu/fp-simd"]
default = []

[dependencies]
axconfig-macros = "0.2"
memory_addr = "0.4"
kspin = "0.1"
axcpu = "0.2"
arm_pl011 = "0.1"
lazy_static = { version = "1.5", features = ["spin_no_std"] }
page_table_entry = "0.6"
aarch32-cpu = "0.2"
log = "0.4"
axplat = { workspace = true }
axplat-aarch64-peripherals = { workspace = true }
